import "./globals.css";

import { Alegreya, Playfair_Display, } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const alegreya = Alegreya({
  subsets: ['latin'],
})
const playfair = Playfair_Display({
  subsets: ['latin'],
})
export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        {children}
      </body>
    </html>
  );
}
